#!/bin/sh

platform_init_enabled() {
	return 0
}

platform_init_run() {
	install_uefi_keys

	__debug "Loading platform devices / drivers ..."

	# load modules for devices
	load_kernel_module gpio-nife200
        load_kernel_module platform-nife200

	__debug "Exporting the platform gpios ..."
	for gc in $(ls -d /sys/class/gpio/gpiochip*); do
	    if grep "iodev" $gc/label; then
    	        gpio=$(cat $gc/base)
		gpiobase=${gpio}
		gpiomax=$(($gpio+$(cat $gc/ngpio)))
		while [ ${gpio} -lt ${gpiomax} ]; do
		    echo ${gpio} > /sys/class/gpio/export
		    gpio=$((gpio+1))
		done
	    fi
	done

	__debug "Creating platform symlinks ..."

	# GPIO outputs
	ln -s /sys/class/gpio/gpio$((gpiobase+0))/value  /var/platform/out_gpo0
	ln -s /sys/class/gpio/gpio$((gpiobase+1))/value  /var/platform/out_gpo1
	ln -s /sys/class/gpio/gpio$((gpiobase+2))/value  /var/platform/out_gpo2
	ln -s /sys/class/gpio/gpio$((gpiobase+3))/value  /var/platform/out_gpo3

	# GPIO inputs
	ln -s /sys/class/gpio/gpio$((gpiobase+4))/value  /var/platform/in_gpi0
	ln -s /sys/class/gpio/gpio$((gpiobase+5))/value  /var/platform/in_gpi1
	ln -s /sys/class/gpio/gpio$((gpiobase+6))/value  /var/platform/in_gpi2
	ln -s /sys/class/gpio/gpio$((gpiobase+7))/value  /var/platform/in_gpi3

  	# LEDs
  	ln -s /sys/class/leds/pg0:orange:user/brightness  /var/platform/led_pg0
	ln -s /sys/class/leds/pg1:green:user/brightness   /var/platform/led_pg1
  	ln -s /sys/class/leds/pg2:orange:user/brightness  /var/platform/led_pg2
  	ln -s /sys/class/leds/pg3:orange:user/brightness  /var/platform/led_pg3
  	ln -s /sys/class/leds/pg4:orange:user/brightness  /var/platform/led_pg4

	ln -s /sys/class/leds/pg1:green:user/brightness   /var/platform/update_led
}
