#!/bin/sh

platform_init_enabled() {
	return 0
}

find_hwid() {
	tmp_dir=$(mktemp -d)
	_hwid=""
	# Use reverse order from save, to be able to overwrite the hwid (e.g. if we get it from the cloud in future)
	for _hwid_label in backup system rescue; do
		_tmp_dev=$(blkid | grep "LABEL=\"${_hwid_label}\"" | cut -d ":" -f1)
		[ -n "${_tmp_dev}" ] && mount ${_tmp_dev} $tmp_dir || continue

		if [ -e $tmp_dir/.unique_id ]; then
			_hwid=$(cat $tmp_dir/.unique_id)
		fi

		umount $tmp_dir
		[ -n "${_hwid}" ] && break
	done
	rmdir $tmp_dir

	echo "${_hwid}"
}

save_hwid() {
	hwid=$1

	# Save to UEFI
	printf "\x07\x00\x00\x00" > /tmp/encid
	echo "${hwid}" >> /tmp/encid
	cat /tmp/encid > /sys/firmware/efi/efivars/hmi-45cd6521-a671-4782-8119-c29a709d2574
	rm /tmp/encid

	# Backup on filesystem
	tmp_dir=$(mktemp -d)
	for _hwid_label in rescue system backup; do
		_tmp_dev=$(blkid | grep "LABEL=\"${_hwid_label}\"" | cut -d ":" -f1)
		[ -n "${_tmp_dev}" ] && mount ${_tmp_dev} $tmp_dir || continue

		# Only update file if not existing or content is different. This ensures the hwid
		# is available in all places (it won't be on backup on first boot, as this step
		# runs before initial partition manager and hwid might be updated in future
		if [ "$(cat $tmp_dir/.unique_id 2>/dev/null)" != "$hwid" ]; then
			echo "$hwid" > $tmp_dir/.unique_id
			sync
		fi

		umount $tmp_dir
	done
	rmdir $tmp_dir
}

platform_init_run() {
	/bin/install_uefi_keys

	# We need the pub key loader to access the certificate
	load_kernel_module pub-key-loader

	mount -t efivarfs none /sys/firmware/efi/efivars
	if [ ! -e "/sys/firmware/efi/efivars/hmi-45cd6521-a671-4782-8119-c29a709d2574" ]; then
		encrypted_id=$(find_hwid)

		if [ -n "${encrypted_id}" ]; then
			echo "UEFI does not support persistent variables, using the one on boot partition"
		else
			echo "Creating unique platform id ..."
			unique_id=$(dd if=/dev/urandom count=256 bs=1 2>/dev/null | sha256sum | cut -d ' ' -f1)
			modulus=$(openssl x509 -noout -modulus -in /proc/sys/srm/owner-cert | cut -d '=' -f2)
			encrypted_id=$(echo $unique_id | openssl aes-256-cbc -nosalt -a -e -k "$modulus" -pbkdf2)
		fi

		save_hwid "${encrypted_id}"
	fi
	umount /sys/firmware/efi/efivars

	echo "Loading platform devices / drivers ..."

	echo "Creating platform symlinks ..."

	mkdir -p /var/platform
	mount -t tmpfs tmpfs /var/platform
}
