MACHINE_FEATURES:append = " tpm tpm2"

require include/intel-common.inc

PRECONFIGURED_SYSTEM_CONNECTIONS ?= "eth0"
PREFERRED_VERSION_linux-stable-rt := "5.15.%"
KERNEL_FEATURES:append:pn-linux-stable-rt := " bsp/intel-x86/intel-x86-64.scc"
