MACHINE_FEATURES:append = " tpm tpm2"

require include/intel-common.inc

INSTALL_UEFI_KEYS = "0"
KERNEL_CMDLINE = "rootflags=noatime overlayflags=noatime,discard ro rootwait rootdelay=1 roottimeout=10 loglevel=4"

PRECONFIGURED_SYSTEM_CONNECTIONS ?= "eth0"
KERNEL_FEATURES:append:pn-linux-stable-rt := " bsp/intel-x86/intel-x86-64.scc"

# Allow nvme and eMMC devices
PHYSICAL_SYSTEM_DEVICE ??= "/dev/nvme0n1 /dev/mmcblk0 /dev/sda /dev/hda"
