#@TYPE: Machine
#@NAME: NETFIELD COMPACT X86C
#@DESCRIPTION:
#@PARTNUMBERS:
#@MAINTAINER: Hilscher Gesellschaft fuer Systemautomation mbH
#@TEMPLATECONF: meta-hilscher-netfield-intel/conf/samples

MACHINE_FEATURES_append += "tpm tpm2"

require include/intel-common.inc

PREFERRED_VERSION_linux-stable-rt = "5.15.%"

PRECONFIGURED_SYSTEM_CONNECTIONS ?= "eth0"
