#@TYPE: Machine
#@NAME: NFX86-D4-N64-021
#@DESCRIPTION: netFIELD Unity
#@PARTNUMBERS: 1918.021
#@MAINTAINER: Hilscher Gesellschaft fuer Systemautomation mbH
#@TEMPLATECONF: meta-hilscher-netfield-intel/conf/samples

require include/intel-common.inc

MACHINE_FEATURES:append = " tpm tpm2"
PRECONFIGURED_SYSTEM_CONNECTIONS ?= "eth0 eth1"
KERNEL_FEATURES:append:pn-linux-stable-rt = " \
    bsp/intel-x86/intel-x86-64.scc \
    features/mei/mei-me.scc \
"
INSTALL_UEFI_KEYS = "0"
KERNEL_CMDLINE = "rootflags=noatime overlayflags=noatime,discard ro rootwait rootdelay=1 roottimeout=10 loglevel=4"

MACHINE_ESSENTIAL_EXTRA_RRECOMMENDS:append = " \
    linux-firmware-i915 \
"
