#@TYPE: Machine
#@NAME: NFX86-D4-N64-020
#@DESCRIPTION:
#@PARTNUMBERS: 1918.020
#@MAINTAINER: Hilscher Gesellschaft fuer Systemautomation mbH
#@TEMPLATECONF: meta-hilscher-netfield-intel/conf/samples

require include/intel-common.inc

MACHINE_FEATURES_append += "tpm tpm2 wifi"
PRECONFIGURED_SYSTEM_CONNECTIONS ?= "eth0 eth1"
PHYSICAL_SYSTEM_DEVICE := "/dev/nvme0n1 /dev/mmcblk0"

# Make sure wifi and bt firmware are included
MACHINE_ESSENTIAL_EXTRA_RRECOMMENDS_append += "linux-firmware-iwlwifi-misc linux-firmware-ibt"
