# Virtual Machine (VMWare / KVM)
SERIAL_CONSOLES = ""

MACHINE_FEATURES_append += "tpm tpm2"

require include/intel-common.inc

PRECONFIGURED_SYSTEM_CONNECTIONS ?= "eth0"

IMAGE_CLASSES_append += "image_types_ova"
OVA_DISKIMAGE_SIZE = "16G"
NETFIELD_IMAGES = ""

IMAGE_PART_BOOT_SIZE = "64M"
PART_DATA_LV_DATA_SIZE = "100%FREE"
# Make sure backup partition has enough space for updates
PART_DATA_LV_BACKUP_SIZE = "640M"
