SERIAL_CONSOLES = ""

MACHINE_FEATURES_append += "tpm"

require include/intel-common.inc
PRECONFIGURED_SYSTEM_CONNECTIONS ?= "eth0 eth1"

# Physical device of system partitions
PHYSICAL_SYSTEM_DEVICE ?= "/dev/sda /dev/hda"
