# We have a conf and classes directory, add to BBPATH
BBPATH := "${BBPATH}:${LAYERDIR}"

# We have a recipes directory, add to BBFILES
BBFILES := "${BBFILES} ${LAYERDIR}/recipes-*/*/*.bb \
	    ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "hilscher-netfield-intel"
BBFILE_PATTERN_hilscher-netfield-intel := "^${LAYERDIR}/"
BBFILE_PRIORITY_hilscher-netfield-intel = "100"

LAYERSERIES_COMPAT_hilscher-netfield-intel = "dunfell"
LAYERDEPENDS_hilscher-netfield-intel = "hilscher-netfield"

KEYS_DIR := "${LAYERDIR}/keys"
